<?php
use PHPMailer\PHPMailer\PHPMailer;
use PHPMailer\PHPMailer\Exception;
session_start(); 
  if(empty($_SESSION)){
     header("Location: index.php");
  }
//Load Composer's autoloader
session_start();
require 'libraries/vendor/autoload.php';
require 'dbcon/db_conn.php';
if(!empty($_POST))
{
	$donor_id = $_SESSION['id'];
	$reciever_id = $_POST['reciever_id'];
	$c_id = $_POST['c_id'];
	$amount = $_POST['amount'];
	$description = $_POST['description'];
	$status = 1;
	$created_at = date('Y-m-d H:m:s');

	$sql1 = "SELECT * FROM categories WHERE id = '$c_id'";
	$result = $conn->query($sql1);
	$row = $result->fetch_assoc();
	$cat_name = $row['name'];

	$sql2 = "SELECT * FROM user WHERE id = '$donor_id'";
	$result1 = $conn->query($sql2);
	$row1 = $result1->fetch_assoc();
	
	$fullname = $row1['fname'].'-'.$row1['lname'];
	$email =$row1['emailid'];

	$sql = "INSERT INTO donation_master (`donor_id`, `reciever_id`,`c_id`,`amount`,`description`,`status`,`created_at`)
		VALUES ('$donor_id','$reciever_id','$c_id','$amount','$description','$status','$created_at')";

		if ($conn->query($sql) === TRUE) 
		{
			$last_id = $conn->insert_id;
			$mail = new PHPMailer(true);                              // Passing `true` enables exceptions
			try 
			{
			    //Server settings
			    //$mail->SMTPDebug = 2;                                 // Enable verbose debug output
			    $mail->isSMTP();                                      // Set mailer to use SMTP
			    $mail->Host = ' smtp.gmail.com';  // Specify main and backup SMTP servers
			    $mail->SMTPAuth = true;                               // Enable SMTP authentication
			    $mail->Username = 'charity.board2018@gmail.com';                 // SMTP username
			    $mail->Password = 'admin.mrsoni01';                           // SMTP password
			    $mail->SMTPSecure = 'tls';                            // Enable TLS encryption, `ssl` also accepted
			    $mail->Port = 587;                                    // TCP port to connect to

			    //Recipients
			    $mail->setFrom('from@example.com', 'Charity');
			    $mail->addAddress($email, $fullname);     // Add a recipient
			    $html = "<table width='100%'' border='0' >
            <tr>
                <td colspan='3'>
                    <table  width='100%'>
                        <tr>
                            <td colspan='2'>
                                <h1><img src='img/logo.png' style='width:200px; height: 100px;'></h1>
                            </td>
                            <td align='center'>
                                <h3>Date:".$created_at."</h3>
                            </td>
                        </tr>
                        <tr>
                            <td colspan='3' align='center'>
                                <h3>Invoice Id:".$last_id."</h3>
                            </td>
                        </tr>
                    </table>
                </td>
            </tr>
            
            <tr>
                <td colspan='3'>
                    <table  width='100%'>
                        <tr>
                            <td colspan='3'>
                               <center><h2>Donation Receipt</h2></center>
                            </td>
                        </tr>
                    </table>
                </td>
            </tr>
            
            <tr style='text-align: center; background: rgba(178, 176, 176,.5); width: 50px;' >
                <td>
                   <h3>Donated By</h3>
                </td>
                <td>
                    <h3>Categories</h3>
                </td>
                <td>
                    <h3>Amount</h3>
                </td>
            </tr>
            <tr style='text-align: center; background: rgba(219, 217, 217,.5); width: 50px;'>
                <td>
                    ".$fullname."
                </td>
                <td>
                    ".$cat_name."
                </td>
                <td>
                    ".$amount."
                </td>
            </tr>
            
            <tr class='total'>
                <td></td>
                
                <td><center>
                  <br><br> <i><b>This is confirmed payment receipt generated by system</i></b>
                </td></center>
            </tr>
        </table>";
			    
			    //Content
			    $mail->isHTML(true);                                  // Set email format to HTML
			    $mail->Subject = 'Donation Receipt';
			    $mail->Body    = $html;

			    $mail->send();
			    header("Location: donate_now_category.php?id=$c_id");
			} catch (Exception $e) {
			    echo 'Message could not be sent. Mailer Error: ', $mail->ErrorInfo;
			}
		}
}
?>
<h2>Below is your donation history</h2>
			    		<p>Here is your donation history receipt:</p>
			    		<table border=1px;>
			    		<tr>
			    			<th>Doner Name</th>
			    			<th>Donation Category</th>
			    			<th>Donation amount</th>
			    			<th>Donation date</th>
			    		</tr>
			    		<tr>
			    			<td>".$fullname."</td>
			    			<td>".$cat_name."</td>
			    			<td>".$amount."</td>
			    			<td>".date('Y-m-d')."</td>
			    		</tr>
			    		</table>